### ISSUE TITLE
两个容器相互拖拽时有时拖拽会没有反应

### ISSUE THREAD

**Issue by 123flight** [YGYOOO/react-draggable-tags#105]
#### 环境：
react：16.14.0
#### 场景：
将 tag1 从 容器 A 拖拽到容器 B 中时，tag1 在容器 B 中进行拖拽操作没有反应。
#### 问题：
经过对源代码调试发现是接收不到 props 变化，导致没有触发 onChange 事件
#### 解决方案：
将 UNSAFE_componentWillReceiveProps 改为 componentWillReceiveProps

**Comment by YGYOOO** [comment]
你好react 16.14.0是5年前的版本了，不考虑支持了，你可以用patch-packag自己修改一下本地node_modules源码
