### ISSUE TITLE
受控组件报错？？？？

### ISSUE THREAD

**Issue by zpaaa** [YGYOOO/react-draggable-tags#13]
![image](https://user-images.githubusercontent.com/37869987/50372624-cc642480-060c-11e9-8d43-ba3d074d7caf.png)

当我添加tag的时候

**Comment by zpaaa** [comment]
解决了，好像不支持push 数组。。

**Comment by YGYOOO** [comment]
是的，整个“tags”数组里每个元素必须得是带id属性的对象，如果需要tags内嵌套tags，可以参考例子
