### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by fengtt** [YGYOOO/react-draggable-tags#14]
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-draggable-tags/lib/bundle.js:1:7702

Read more here: http://bit.ly/2tRViJ9

start开发的时候不会报错  但是打包报错  是最新的0.2.8版本

**Comment by fengtt** [comment]
[webpack.txt](https://github.com/YGYOOO/react-draggable-tags/files/2709863/webpack.txt)

**Comment by YGYOOO** [comment]
刚更新了一下打包方式，请升级到0.2.9试一下？
