### ISSUE TITLE
add empty element

### ISSUE THREAD

**Issue by detanx** [YGYOOO/react-draggable-tags#15]
When I don't type anything in the input box that adds the element, then click the add button. Will add a empty element to the DOM, so I think you should check if the input is empty before clicking the add button.
![image](https://user-images.githubusercontent.com/22371912/50534814-42bcd580-0b7d-11e9-9f54-b37520cc7757.png)

**Comment by YGYOOO** [comment]
Thanks for your advice. I have noticed this problem. I thought it's just a simple demo, so I didn't expect it to be robust. Maybe I will fix it later. 😝
