### ISSUE TITLE
在react中，一组数据中，只有最后一项可拖拽，其他项不能拖拽，还有怎么指定key?

### ISSUE THREAD

**Issue by Kdze** [YGYOOO/react-draggable-tags#16]

**Comment by Kdze** [comment]
[index.zip](https://github.com/YGYOOO/react-draggable-tags/files/2734994/index.zip)
![errkey](https://user-images.githubusercontent.com/33314614/50806544-26b1f480-1332-11e9-9e9d-88c70b56b19c.jpg)

**Comment by YGYOOO** [comment]
首先，这段代码里对DraggableArea的用法有个问题，如果使用了tags属性而非initialTags属性，则当前DraggableArea就是“受控组件”，tags顺序的变动需要你来执行，即每次onChange时需要执行setState，函数可以这么写departmentList => this.setState({departmentList})。（可以参考示例中的"Controlled" Tags）。
至于react报的key相关的错误，如果定位到确实是DraggableArea中报的错，建议检查一下是否departmentList中每个对象都有id属性，且这些id都是唯一的。（可以试下把departmentList设为你那个[{id: 1,name: 'apple'}, {id: 2,name: 'red'},...]，然后不请求接口，看看可不可以）

**Comment by Kdze** [comment]
不用请求的数据是可以 但我要使用后台返回的数据改怎么用呢

**Comment by YGYOOO** [comment]
那你得check一下返回的数据是否是一个数组，且其中每个元素都有id字段，且id唯一，如果这些没问题，那不应该会报错了

**Comment by YGYOOO** [comment]
或者你可以把返回的数据给我看一下

**Comment by Kdze** [comment]
![data](https://user-images.githubusercontent.com/33314614/50816408-73f68c00-135b-11e9-9220-5a362b2a2183.png)

**Comment by YGYOOO** [comment]
没有id呀，拿到数据后你可以先给每个对象加一个“id”字段，值与“department_id”相同，然后setState
