### ISSUE TITLE
Uncaught TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by shubingzhou** [YGYOOO/react-draggable-tags#2]
很简单的使用然后报这个错呢？

![image](https://user-images.githubusercontent.com/20392408/41921768-2cc448f4-7996-11e8-95d3-7c46c4f61cf5.png)

![image](https://user-images.githubusercontent.com/20392408/41921446-784a572e-7995-11e8-86ac-3c0427d9e92f.png)

**Comment by aiqin-bao** [comment]
你解决了吗 ？

**Comment by YGYOOO** [comment]
不好意思，前段时间有点忙没过来看一眼，这么晚才回复。
这个应该因为你的react版本跟react-draggable-tags里要求的不一致（你是不是react16？），我现在做了修改，react16也可以正常使用了，应该不会再报以上问题，请更新最新版本react-draggable-tags看看。（目前最新是0.2.1）

**Comment by aiqin-bao** [comment]
好的～

**Comment by sjyMystery** [comment]
0.2.5还是有这个问题 如果我换成16.7

**Comment by YGYOOO** [comment]
@sjyMystery 请试一下我刚发布的0.2.7版本，这个版本应该可以支持react大于15.0的所有版本
