### ISSUE TITLE
不管怎样都能拖和放，这就没法限制条件去放置了

### ISSUE THREAD

**Issue by tzf2625** [YGYOOO/react-draggable-tags#21]

**Comment by YGYOOO** [comment]
你的意思是限制某些tag无法拖动吗

**Comment by YGYOOO** [comment]
刚发布了3.0.1版本，若某个tag的undraggable值为true则不可拖拽，可以尝试一下，例子见：https://ygyooo.github.io/react-draggable-tags 的“Simple Usage”。
如果需要比较复杂的限制的话，可以在onChange的时候自己做相应判断，然后决定是否更新，如：
onChange={tags => {
              if (...) {
                // 更新
                this.setState({tags});
              } else {
                this.setState({tags: this.state.tags});
              }
            }}

**Comment by tzf2625** [comment]
我起初的意思是：没法做到完全可控，如果目标区域不是拖拽物该去的，那就应该放不进去。

**Comment by YGYOOO** [comment]
比如“tagA不能放到tagB的左边”？

**Comment by tzf2625** [comment]
前提：跨区域。
例：金鱼箱里的金鱼可以放到鲤鱼箱（各种鱼类箱），但不能放到蜘蛛箱里（各种节肢动物）。

**Comment by tzf2625** [comment]
好的，你的组件比较“轻”，所以个人比较喜欢。由于之前无法实现需求，就换成了react-beautiful-dnd。
总之还是感谢。

**Comment by YGYOOO** [comment]
好的，谢谢你的建议

**Comment by YGYOOO** [comment]
刚发布了最新版本0.3.4，已可以实现根据相应条件拖拽。
具体例子见： https://ygyooo.github.io/react-draggable-tags#CrossAreaRestriction
