### ISSUE TITLE
可以限制拖拽吗

### ISSUE THREAD

**Issue by zuoqiyin** [YGYOOO/react-draggable-tags#22]

**Comment by YGYOOO** [comment]
如果是限制某一个tag能否被拖拽的话，可以看https://ygyooo.github.io/react-draggable-tags/里simple usage，把这个tag的undraggable设为true即可

**Comment by YGYOOO** [comment]
我有考虑过之后加上集合之间能否拖动的限制条件。有时间的话我今晚出一版。

另外，即使用现有版本也可以实现你说的功能，参考：https://github.com/YGYOOO/react-draggable-tags/issues/21#issuecomment-454316169  。当然这种方法很麻烦，不建议用。

**Comment by YGYOOO** [comment]
刚发布了最新版本0.3.4，你可以参照这个例子实现相应功能 https://ygyooo.github.io/react-draggable-tags#CrossAreaRestriction

**Comment by zuoqiyin** [comment]
还建议增加一个同一个集合中是否排序这个属性

**Comment by zuoqiyin** [comment]
还有可否增加一个动态增加可拖放区域功能

**Comment by YGYOOO** [comment]
请问“同一个集合中是否排序”是什么意思？
对于第二条，目前能作为“可拖放区域”的只有DraggableArea，也完全可以“动态”增加一个DraggableArea。还是说你指的是动态添加一个DraggableArea到某个group中？

**Comment by zuoqiyin** [comment]
1.同一个集合中是否排序，就是集合A中的元素不能在集合A中拖放，只能拖到其他集合中。
2.动态添加一个DraggableArea到某个group中

**Comment by zuoqiyin** [comment]
关于动态添加，比如在格栅布局的时候开始是2列，里面有个两个DraggableArea现在动态的给换成3列，需要在加一个DraggableArea

**Comment by YGYOOO** [comment]
比如这样动态添加：
const newArea =  group.addArea();
this.setState({draggableAreas: [...this.state.draggableAreas, newArea]});
在render方法里：
<div>
  {this.state.draggableAreas.map(Area => (
    <Area />
  ))}
</div>

本身react中的jsx标签就是个变量（除了原生的html标签），准确说是个类或者function

**Comment by zuoqiyin** [comment]
好的，这个我有空试试，我还是建议在Draggable中加个group属性去标识是哪个组中的，这样就不用addArea()出来一个新的，类似vue Draggable那样，你看看可否？

**Comment by zuoqiyin** [comment]
场景跟你这个差不多，就是你这个每次都要`addArea`重新定义一个感觉有点麻烦，如果都用同一个标签`<Draggable />`不同的group就是增加一些属性就行了，这样动态添加一个也更方便一点了

**Comment by YGYOOO** [comment]
哦，懂了，这样确实比较方便，不过实现机制不太一样，改动的话可能也会影响到之前一些api，我有时间的时候想一下

**Comment by zuoqiyin** [comment]
总体上你这个还是可以满足大部分的需求，我到时候遇到具体的，在来问你
