### ISSUE TITLE
关于嵌套问题

### ISSUE THREAD

**Issue by zuoqiyin** [YGYOOO/react-draggable-tags#23]
![image](https://user-images.githubusercontent.com/30616400/51456683-9fc93700-1d89-11e9-91b8-c11a0a61e9eb.png)
这种嵌套的话，单行文本，就不能拖拽到灰色区域了

**Comment by zuoqiyin** [comment]
![image](https://user-images.githubusercontent.com/30616400/51456967-870d5100-1d8a-11e9-8751-28e379d376bb.png)
A区域的元素单行文本不能拖入B区域中

**Comment by YGYOOO** [comment]
是的，现在只支持同级tag之间的拖拽，这种跨层级拖拽的功能实现需要比较大的修改，api可能也要改，所以近期不考虑增加该功能。

**Comment by YGYOOO** [comment]
近期不考虑添加该功能
