### ISSUE TITLE
最新版本更新什么东西了吗？

### ISSUE THREAD

**Issue by movecodeman** [YGYOOO/react-draggable-tags#29]

**Comment by YGYOOO** [comment]
请问你是更新版本后出现什么问题了吗？从什么版本到什么版本？
0.3.5版本相比0.3.4新增了“undraggable tag”功能，最新特性见：https://ygyooo.github.io/react-draggable-tags/

**Comment by movecodeman** [comment]
功能很好，没有什么问题，公司项目在用，希望早日更新拖拽插入时可选插入位置功能

**Comment by movecodeman** [comment]
就是第一个评论说的问题，我也觉得很有必要

**Comment by YGYOOO** [comment]
好的，既然这么多人要求那我抽空实现下！

**Comment by YGYOOO** [comment]
版本0.4.0-beta.1已支持跨区域拖拽插入相应位置。
该版本改动较大，不排除有新的bug，建议细心使用。
