### ISSUE TITLE
使用webpack打包时怎么排除压缩该库？

### ISSUE THREAD

**Issue by andares** [YGYOOO/react-draggable-tags#3]
npm i安装后是压缩过的bundle，npm使用webpack统一打包的时候会报无法minify该文件的错误导致打包失败。

问下怎么排除该库？或者有提供其他安装方式比如源码npm i方便统一打包吗？

**Comment by YGYOOO** [comment]
请问报的错能复制或者截图给我看一下吗？

**Comment by andares** [comment]
![default](https://user-images.githubusercontent.com/7556505/43701784-16a5eaf0-998a-11e8-8e9b-b346e8c72e9f.png)

**Comment by andares** [comment]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

react有说了几种解决方案。我这边尝试fork一个库发布了源码，但编译时报错：

./node_modules/react-draggable-tags-raw/src/DraggableAreaBuilder.js
Module parse failed: Unexpected token (316:8)
You may need an appropriate loader to handle this file type.
|       if (!render) render = build;
|       const tags = this.state.tags.toJS().map((tag) => (
|         <div
|           key={tag.id}
|           className="DraggableTags-tag"

**Comment by YGYOOO** [comment]
因为无法重现你的问题，我也没啥头绪，但你那个编译报错看上去是因为没配置好babel？316行是<div那行吗？得配置支持jsx

**Comment by andares** [comment]
看react那个页面说可能跟打包模式有关。不过好在代码量不大，我们前端给拿出来整合进项目了 😂 

之后再说吧，我感觉这边的react项目也是建得有点问题。
