### ISSUE TITLE
crossArea 数据跨区域

### ISSUE THREAD

**Issue by huangxiaohao** [YGYOOO/react-draggable-tags#30]
您好，目前使用您的插件碰到一个问题：
左右两个区域
![image](https://user-images.githubusercontent.com/13390763/60247794-e94b1e80-98f3-11e9-8b76-fc4c11986a8b.png)
1.左边区域可以移动到右边，右边不能移动到左边
2.当将“6”从左边移动到右边，右边区域增加，但是左边区域数量不变，还是“4，5，6”
请问这个如何处理 谢谢！

**Comment by YGYOOO** [comment]
应该是使用有误，你可以把这个例子复制过来https://ygyooo.github.io/react-draggable-tags/#CrossAreaDrag，试一下是否正常运行。
感觉是少了个onChange方法，或者onChange方法里没有正确地setState
