### ISSUE TITLE
tag不能跨区域随机拖到另一个区域的指定位置

### ISSUE THREAD

**Issue by zhanghuohuo1996** [YGYOOO/react-draggable-tags#31]
您好，现在小tag不能跨区域随机拖到另一个区域的指定位置，只能拖拽到最后的位置，请问有合适解决方法吗？希望得到您的回复，感谢。
![image](https://user-images.githubusercontent.com/22960145/60312213-05e76500-998d-11e9-9637-b99885f83a78.png)
![image](https://user-images.githubusercontent.com/22960145/60312247-2e6f5f00-998d-11e9-84e3-734e4dad6668.png)

**Comment by YGYOOO** [comment]
可以升级到0.4.0-beta.2试一下，支持跨区域拖拽到鼠标松开时的位置

**Comment by zhanghuohuo1996** [comment]
> 可以升级到0.4.0-beta.2试一下，支持跨区域拖拽到鼠标松开时的位置

谢谢您的回复，试了还是不行，没有变化，请问还有别的解决办法吗？

**Comment by zhanghuohuo1996** [comment]
> 可以升级到0.4.0-beta.2试一下，支持跨区域拖拽到鼠标松开时的位置

还是升级包以后，组件需要其他特殊属性的设置？

**Comment by YGYOOO** [comment]
不用呀，不知道我又没有理解错，你试下https://ygyooo.github.io/react-draggable-tags/#CrossAreaDrag 这个例子是否满足你说的（虽然这个不是list但效果一样，如果要变成list只要加个isList）
