### ISSUE TITLE
标签可编辑

### ISSUE THREAD

**Issue by tancgo** [YGYOOO/react-draggable-tags#32]
请问可以支持标签直接编辑的功能么

**Comment by YGYOOO** [comment]
没明白啥意思，“标签”是什么是你自己决定的，react-draggable-tags只提供各种拖拽功能，至于拖拽的是什么东西，完全看你写的是啥啊，每个标签是input也可以啊，
比如render方法里
render={({tag, index}) => (
      <Input value={tag.content} onChange={...} />
    )}
你指的编辑是？
