### ISSUE TITLE
结合另外一个拖拽组件不能正常拖拽

### ISSUE THREAD

**Issue by Icacls** [YGYOOO/react-draggable-tags#35]
项目有个需求需要结合react-beautiful-dnd完成，但是嵌套使用的情况下组件的拖拽行为变得很奇怪。
Demo如下 [Demo](https://codesandbox.io/s/nice-shockley-jq9y8) 能否帮忙定位下原因。

**Comment by YGYOOO** [comment]
![image](https://user-images.githubusercontent.com/15754991/69948935-7b9ec080-152b-11ea-95eb-419883deae65.png)
打开后报错了？
