### ISSUE TITLE
怎么在表格中使用这个功能呢

### ISSUE THREAD

**Issue by hdyusf** [YGYOOO/react-draggable-tags#42]
插件在tr外包了几层div 在表格中报错 `<div> cannot appear as a child of <tbody>`
是否能指定包裹的最外层标签名称

**Comment by YGYOOO** [comment]
不清楚你怎么用这个标签组件的，但该组件肯定是不能和表格耦合起来用的，建议不用table，都用div来模拟表格，或者尝试别的组件
