### ISSUE TITLE
Prevent click when dragging

### ISSUE THREAD

**Issue by isaiahtaylorhh** [YGYOOO/react-draggable-tags#45]
When dragging an element, use `stopPropogation` and `preventDefault` to stop the click event.

**Comment by isaiahtaylor** [comment]
Interestingly, this only appears to be an issue when dragging *backwards* in the list.

**Comment by YGYOOO** [comment]
Hi, the latest version 1.0.0 has been published which prevents click event when dragging.

**Comment by zhongxiaopang** [comment]
@YGYOOO 最新版本还是有这个问题

**Comment by YGYOOO** [comment]
> @YGYOOO 最新版本还是有这个问题

建议按照以下步骤排查：
1、npm list react-draggable-tags确保你当前的版本为1.0.0;
2、执行以下代码看是否有问题：
const initialTags = [
  {id: 1, content: 'apple'}, {id: 2, content: 'olive'}, {id: 3, content: <div onClick={() => console.log(1111)}>test</div>},
  {id: 4,  content: 'lemon'}, {id: 5, content: 'orange'}, {id: 6, content: 'grape'},
  {id: 7, content: 'strawberry'}, {id: 8, content: 'cherry'}, {id: 9, content: 'peach'}];

export default class Main extends Component {
  render() {
    return (
      <div className="Simple">
        <DraggableArea
          tags={initialTags}
          render={({tag, index}) => (
            <div className="tag">
              {tag.content}
            </div>
          )}
          onChange={tags => console.log(tags)}
        />
      </div>
    );
  }
}

**Comment by zhongxiaopang** [comment]
> > @YGYOOO 最新版本还是有这个问题
> 
> 建议按照以下步骤排查：
> 1、npm list react-draggable-tags确保你当前的版本为1.0.0;
> 2、执行以下代码看是否有问题：
> const initialTags = [
> {id: 1, content: 'apple'}, {id: 2, content: 'olive'}, {id: 3, content: <div onClick={() => console.log(1111)}>test},
> {id: 4, content: 'lemon'}, {id: 5, content: 'orange'}, {id: 6, content: 'grape'},
> {id: 7, content: 'strawberry'}, {id: 8, content: 'cherry'}, {id: 9, content: 'peach'}];
> 
> export default class Main extends Component {
> render() {
> return (
> 
> <DraggableArea
> tags={initialTags}
> render={({tag, index}) => (
> 
> {tag.content}
> 
> )}
> onChange={tags => console.log(tags)}
> />
> 
> );
> }
> }

![image](https://user-images.githubusercontent.com/18260026/89016727-c9cec280-d34b-11ea-8b90-e1fce61c6197.png)
代码是生效的，就是点击按钮拿到当前顺序的数组，需要点击两次才可以

**Comment by YGYOOO** [comment]
> 代码是生效的，就是点击按钮拿到当前顺序的数组，需要点击两次才可以
就是往右拖动后，要点击两次才会触发那个onClick事件对吧？请升级到1.0.1

**Comment by zhongxiaopang** [comment]
对，和楼上说的情况一样，往后拖动，需要点击两次，我升级1.0.1试试

**Comment by zhongxiaopang** [comment]
1.0.1版本发布了吗

**Comment by YGYOOO** [comment]
> 1.0.1版本发布了吗

https://www.npmjs.com/package/react-draggable-tags 发布了的
