### ISSUE TITLE
是否可以添加一个禁止移动的功能

### ISSUE THREAD

**Issue by maimai123** [YGYOOO/react-draggable-tags#50]
某个节点设置disable以后就不允许拖拽

**Comment by YGYOOO** [comment]
你好，在节点上加个undraggable: true就可以了，如initailTags=[{id: 1, content: 'apple', undraggable: true}]

**Comment by maimai123** [comment]
感谢！

**Comment by maimai123** [comment]
唔。。能否有个置顶功能 就是这个元素一直置顶 别的元素不能放到他前面去

**Comment by YGYOOO** [comment]
暂时不支持，后续可以考虑增加该功能。
不过现在你可以实现一半的效果，就是在onChange的时候判断新的tags顺序符不符合条件，不符合就setstate回之前的状态，这样就可以控制一些tag永远置顶（只不过在拖拽过程中可以放到它前面，松开鼠标后才会触发onChange，你再setState回去，这时候确保置顶的tag依然置顶）

**Comment by maimai123** [comment]
嗯嗯！
