### ISSUE TITLE
对象里面一定要有id这个字段吗

### ISSUE THREAD

**Issue by kjl999** [YGYOOO/react-draggable-tags#54]

**Comment by YGYOOO** [comment]
是的呢，目前是这样设计的，必须要有唯一标识，才能确认整个list怎么变化了（是改变顺序了还是添加修改删除了）

**Comment by kjl999** [comment]
> 是的呢，目前是这样设计的，必须要有唯一标识，才能确认整个list怎么变化了（是改变顺序了还是添加修改删除了）

意思没有id这个字段，就无法拖拽吗，好像我把id去掉，有的时候首次能拖拽，后面又拖拽不了，比如现在我有一个数组，数组里面有多个对象，对象里面需要根据后台传来的某个字段来决定是否能拖拽排序，然后我把相对应的对象里面的id删除，发现第一次拖拽那个对象元素的时候，还是能拖拽，后面就无法拖拽了

**Comment by YGYOOO** [comment]
是的必须要有id

**Comment by kjl999** [comment]
> 是的必须要有id
