### ISSUE TITLE
参考了哪里的设计呀

### ISSUE THREAD

**Issue by mezhanglei** [YGYOOO/react-draggable-tags#55]

**Comment by YGYOOO** [comment]
没有参考。。。为啥会提这个issue。。。

**Comment by mezhanglei** [comment]
哈哈，我看了一遍，然后看到有些奇怪的地方，以为作者瞎写呢

**Comment by YGYOOO** [comment]
啥情况呀，哪边奇怪

**Comment by mezhanglei** [comment]
代码有些冗余,可以精简一下,比如componentWillRecieved和componentDidUpdate这里可以合并为一个. 
componentDidUpdate(prevProps) {
            if (!this.props.tags) {
                return;
            }
            if (prevProps.tags.length !== this.props.tags.length ||
                prevProps.tags.some((tag, i) => !this.props.tags[i] || tag.id !== this.props.tags[i].id)) {
                this.setTags(List(this.props.tags));
            }
        }
然后计算坐标这里:
if (curBaseLeft > prevBaseLeft) {
                  elmnt.style.left = `${l - (curBaseLeft - prevBaseLeft)}px`;
                } else {
                  elmnt.style.left = `${l + (prevBaseLeft - curBaseLeft)}px`;
                }
                if (prevBaseTop > curBaseTop) {
                  elmnt.style.top = `${t + (prevBaseTop - curBaseTop)}px`;
                } else {
                  elmnt.style.top = `${t - (curBaseTop - prevBaseTop)}px`;
                }
其实就是: 
elmnt.style.left = `${dragLeft - (curBaseLeft - prevBaseLeft)}px`;
 elmnt.style.top = `${dragTop - (curBaseTop - prevBaseTop)}px`;
哈哈,设计思路非常优秀,只是一些小瑕疵,学习了

**Comment by mezhanglei** [comment]
其余计算坐标的代码还可以精简一百来行左右, 更容易阅读一些,我已经看完了,作者很秀

**Comment by YGYOOO** [comment]
setTags放在didupdate里会多渲染一次，这块部分性能很重要，所以才放在willReceiveProps。
第二个确实可以简化~计算坐标的部分完全是为了代码的可读性，这块也减少不了多少代码体积的（而且计算坐标的部分一共也才一百来行。。。）
