### ISSUE TITLE
Cross Area Placeholder

### ISSUE THREAD

**Issue by clemens1483** [YGYOOO/react-draggable-tags#78]
Hi, I really like this component I just had one small issue with it:

If you have two areas and you drag and drop from area 1 to area 2, the placeholder is inserted in area 1 instead of area 2 and tags move in area 1 instead of area 2.

![react-draggable-tags](https://user-images.githubusercontent.com/55035592/130097464-e3b9cede-f9ee-4072-ba68-299988b91672.gif)

this also happens in the Cross Area Drag Section on the demo page https://ygyooo.github.io/react-draggable-tags/

**Comment by YGYOOO** [comment]
Hi, thanks for using it. Due to the current design, it may be hard to insert the placeholder in area2. But I think I can try to remove the placeholder in area1 to make it not so weird. 
Maybe I will publish the new version of react-draggable-tags in 3 days.

**Comment by clemens1483** [comment]
Hi, thank you for replying so quickly. That would be great!

**Comment by YGYOOO** [comment]
Hi, please update to version 1.0.4.
