### ISSUE TITLE
react打包时候报错

### ISSUE THREAD

**Issue by Wenbo157** [YGYOOO/react-draggable-tags#8]
Failed to minify the code from this file:

        ./node_modules/react-draggable-tags/lib/bundle.js:6:1244

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by YGYOOO** [comment]
请问你是用什么去minify代码的？尝试一下升级至最新版本的react-draggable-tags还有这个问题吗？
