### ISSUE TITLE
[bug] Column of tags doesn't detect drag event 

### ISSUE THREAD

**Issue by manutero** [YGYOOO/react-draggable-tags#87]
A video worth thousand words: 

I've created a demo for showing this issue: 

https://user-images.githubusercontent.com/2211052/148766159-32d37175-a9dc-4c66-b54c-0ba8dea5597a.mov

There is a wrapper div (the column):

```css
      display: 'flex',
      flexWrap: 'wrap',
      width: '100px',
```

And craeting the tags as mentioned on the docs:

```js
     <DraggableArea
        tags={items}
        render={({ tag: item, index }) => (
          <div id={`xxx`} className='ccc'>
            {render(item, index)}
          </div>
        )}
        onChange={onChange}
      ></DraggableArea>
```

As you can see on the video, the draggable area doesn't detect the event till the x axis change

**Comment by YGYOOO** [comment]
Hi, if you want to use it as a list, you could add a "isList" attribute to DraggableArea. Here is the demo: https://ygyooo.github.io/react-draggable-tags/#List

**Comment by manuartero** [comment]
Ok great!

works like a charm ->

https://user-images.githubusercontent.com/2211052/148919551-a7069fb2-33f6-43e0-a413-a7f40f48f9f0.mov
